apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
data:
  DB_NAME: "mydatabase"
  DB_USER: "myuser"
  DB_HOST: "postgresql"-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
  DB_USERNAME: bXl1c2Vy